### PR TITLE
Update subscribe link in site menu

### PR DESCRIPTION
**Pull request by CaitlynKnudsvig**
Per Brittany Bucceroni via BCMS-736
Screen Shot 2020-07-08 at 11 05 26 AM

### CODE REVIEW

**Comment by CaitlynKnudsvig** [comment]
@zarathustra323 / @solocommand - mind deploying this sometime this week?

**Comment by zarathustra323** [comment]
@CaitlynKnudsvig Merged. If you'd like to deploy this I can, otherwise you can using the instructions from last week... `scripts/lerna.sh version patch`

**Comment by CaitlynKnudsvig** [comment]
I don't have enough permissions to assign a reviewer or add labels to this repo, so I'm guessing I won't be able to deploy  either :(

**Comment by CaitlynKnudsvig** [comment]
Actually I take that back I see you updated it just now :) I'll deploy then

**Comment by CaitlynKnudsvig** [comment]
Spoke too soon, might need you to deploy :( 
`remote: error: Required status check "continuous-integration/travis-ci" is expected. At least 1 approving review is required by reviewers with write access.        
lerna ERR! To https://github.com/endeavorb2b/websites.git
lerna ERR!  * [new tag]           v0.15.9 -> v0.15.9
lerna ERR!  ! [remote rejected]   master -> master (protected branch hook declined)
lerna ERR! error: failed to push some refs to 'https://CaitlynKnudsvig@github.com/endeavorb2b/websites.git'`

**Comment by solocommand** [comment]
@CaitlynKnudsvig I created and added you to the @endeavorb2b/legacy-website-maintainers team, which should provide the access you need. @Jlaird has full admin on this organization and is the maintainer of that team if other changes need to be made :)

**Pull request merged**
