### PR TITLE
Reduce header z index to accomodate welcome ads

### PR DESCRIPTION
**Pull request by crandall-endeavor**

### CODE REVIEW

**Comment by CaitlynKnudsvig** [comment]
@crandall-endeavor - this repo only houses ogj.com, was that the intent?

**Review by CaitlynKnudsvig — COMMENTED** [review]
Also, this is a bit nit-picky but was there a reason you moved it out of the site-header scss grouping and down below by the site-navbar grouping?

**Comment by crandall-endeavor** [comment]
> @crandall-endeavor - this repo only houses ogj.com, was that the intent?

Yeah, they’re starting to run welcome ads and the header z-index was too high.

**Comment by crandall-endeavor** [comment]
> Also, this is a bit nit-picky but was there a reason you moved it out of the site-header scss grouping and down below by the site-navbar grouping?

I didn’t really mean to, but saving the file in my IDE completely reformats it so I tried to revert all changes but this one.

**Review by CaitlynKnudsvig — APPROVED** [review]

**Pull request merged**
