### PR TITLE
CS3012-VSD: Deb requested a hero component

### PR DESCRIPTION
**Pull request by Alixers505**
Added a hero component to the top of the Knowledge Zone page.

### CODE REVIEW

**Comment by zarathustra323** [comment]
@Alixers505 Can you provide a screenshot please? :)

**Comment by Alixers505** [comment]
https://southcomm.atlassian.net/projects/CS/queues/custom/30/CS-3012

**Comment by Alixers505** [comment]
The placement of the sticky ad is a result of the screenshot tool.

knowledge-zone

**Comment by zarathustra323** [comment]
@Alixers505 This will also need to be applied to the base-cms-websites/endeavor-business-media repository.

**Pull request closed without merging**
